### ISSUE TITLE
wrong logic

### ISSUE THREAD

**Issue by kalpak44** [WhitexSC/react-begining#1]
https://github.com/WhitexSC/react-begining/blob/72156f6d5a33e051832ce3d0ab5abcd1a51737f0/src/App.js#L7
you realy want to delete from empty array ?

class App extends Component {
	//this.setState() - to update state
    state = {
        characters: [
            {
                'name': 'Charlie',
                'job': 'Janitor'
            },
            {
                'name': 'Mac',
                'job': 'Bouncer'
            },
            {
                'name': 'Dee',
                'job': 'Aspring actress'
            },
            {
                'name': 'Dennis',
                'job': 'Bartender'
            }
        ]        
     };
     
	 removeCharacter = index => {
	   const { characters } = this.state;
		 console.log(this.state);

	   this.setState({
	       characters: characters.filter((character, i) => { 
	           return i !== index;
	       })
	   });
	}

    render() {
   
        // const { characters } = this.setState
		return (
		    <div className="container">
		        <Table
		            characterData={this.state.characters}
		            removeCharacter={this.removeCharacter} 
		        />
		    </div>
		);
    }
}

**Comment by WhitexSC** [comment]
@kalpak44, hello! I've just commited it because I had no time. Now it works. Thanks for your feedback!
